$file = 'c:\Users\Pongo\Downloads\Compressed\newReynaldo-portoflio-main\src\components\portfolio\CreativeVideos.tsx'
$lines = Get-Content $file
$before = $lines[0..660]
$after = $lines[704..($lines.Count-1)]
$new = @(
  "        {/* Info overlay */}",
  "        <div className=""absolute bottom-0 left-0 right-0 p-3 md:p-8"">",
  "          {/* Mobile: emoji-only awards */}",
  "          <div className=""flex items-center gap-1 mb-1 md:hidden"">",
  "            <span",
  "              className=""text-[10px] font-bold px-2 py-0.5 rounded-full text-white whitespace-nowrap""",
  "              style={{ background: accentColor }}",
  "            >",
  "              ✦ FEATURED",
  "            </span>",
  "            {video.awards && video.awards.length > 0",
  "              ? video.awards.map((aw) => (",
  "                  <span key={aw.label} title={aw.label} className=""text-base"">",
  "                    {aw.icon}",
  "                  </span>",
  "                ))",
  "              : video.award && <span className=""text-base"">🏆</span>}",
  "          </div>",
  "          {/* Desktop: full awards with labels */}",
  "          <div className=""hidden md:flex flex-wrap items-center gap-2 mb-2"">",
  "            <span",
  "              className=""text-xs font-bold px-3 py-1 rounded-full text-white""",
  "              style={{ background: accentColor }}",
  "            >",
  "              ✦ FEATURED",
  "            </span>",
  "            {video.awards && video.awards.length > 0",
  "              ? video.awards.map((aw) => (",
  "                  <span",
  "                    key={aw.label}",
  "                    className=""flex items-center gap-1 text-xs font-semibold text-yellow-400 bg-black/40 px-2 py-1 rounded-full backdrop-blur-sm""",
  "                  >",
  "                    {aw.icon} {aw.label}",
  "                  </span>",
  "                ))",
  "              : video.award && (",
  "                  <span className=""flex items-center gap-1 text-xs font-semibold text-yellow-400 bg-black/40 px-2 py-1 rounded-full backdrop-blur-sm"">",
  "                    <Trophy className=""w-3 h-3"" />",
  "                    {video.award}",
  "                  </span>",
  "                )}",
  "          </div>",
  "          <h2 className=""text-white text-sm md:text-3xl font-bold leading-tight mb-0.5 md:mb-1 drop-shadow-lg line-clamp-2"">",
  "            {video.title}",
  "          </h2>",
  "          {video.role && (",
  "            <p className=""text-white/60 text-[10px] md:text-xs mb-0.5"">",
  "              Role:{' '}",
  "              <span className=""text-white/90 font-semibold"">{video.role}</span>",
  "              {video.platform && (",
  "                <span className=""ml-1"">· {video.platform}</span>",
  "              )}",
  "            </p>",
  "          )}",
  "          <p className=""hidden md:block text-white/70 text-base max-w-2xl line-clamp-2"">",
  "            {video.description}",
  "          </p>",
  "          <div className=""flex items-center gap-2 mt-1 md:mt-3"">",
  "            <span className=""text-white/50 text-[10px] md:text-xs flex items-center gap-1"">",
  "              <Calendar className=""w-2.5 h-2.5 md:w-3 md:h-3"" /> {video.year}",
  "            </span>",
  "            <span className=""hidden md:inline text-white/30"">·</span>",
  "            <div className=""hidden md:flex flex-wrap gap-1"">",
  "              {video.tags.slice(0, 3).map((t) => (",
  "                <span key={t} className=""text-white/60 text-xs bg-white/10 px-2 py-0.5 rounded-full"">",
  "                  {t}",
  "                </span>",
  "              ))}",
  "            </div>",
  "          </div>",
  "        </div>"
)
$result = $before + $new + $after
$result | Set-Content $file
Write-Host "Done: $($result.Count) lines"
